/* 
 * HyperFlex AAA [Authentication, Authorization and Accounting]
 *
 * REST API to authenticate users and grant/validate access tokens. AAA provides role based access control to REST APIs which allows users to perform various operations on resources in a cluster.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: techsupport@springpathinc.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AAAConfiguration
    /// </summary>
    [DataContract]
    public partial class AAAConfiguration :  IEquatable<AAAConfiguration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AAAConfiguration" /> class.
        /// </summary>
        /// <param name="SessionTimeout">SessionTimeout.</param>
        /// <param name="WarnSessionTimeout">WarnSessionTimeout.</param>
        public AAAConfiguration(long? SessionTimeout = default(long?), long? WarnSessionTimeout = default(long?))
        {
            this.SessionTimeout = SessionTimeout;
            this.WarnSessionTimeout = WarnSessionTimeout;
        }
        
        /// <summary>
        /// Gets or Sets SessionTimeout
        /// </summary>
        [DataMember(Name="sessionTimeout", EmitDefaultValue=false)]
        public long? SessionTimeout { get; set; }

        /// <summary>
        /// Gets or Sets WarnSessionTimeout
        /// </summary>
        [DataMember(Name="warnSessionTimeout", EmitDefaultValue=false)]
        public long? WarnSessionTimeout { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AAAConfiguration {\n");
            sb.Append("  SessionTimeout: ").Append(SessionTimeout).Append("\n");
            sb.Append("  WarnSessionTimeout: ").Append(WarnSessionTimeout).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AAAConfiguration);
        }

        /// <summary>
        /// Returns true if AAAConfiguration instances are equal
        /// </summary>
        /// <param name="other">Instance of AAAConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AAAConfiguration other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.SessionTimeout == other.SessionTimeout ||
                    this.SessionTimeout != null &&
                    this.SessionTimeout.Equals(other.SessionTimeout)
                ) && 
                (
                    this.WarnSessionTimeout == other.WarnSessionTimeout ||
                    this.WarnSessionTimeout != null &&
                    this.WarnSessionTimeout.Equals(other.WarnSessionTimeout)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.SessionTimeout != null)
                    hash = hash * 59 + this.SessionTimeout.GetHashCode();
                if (this.WarnSessionTimeout != null)
                    hash = hash * 59 + this.WarnSessionTimeout.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
