/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ProtectionGroupInfo
    /// </summary>
    [DataContract]
    public partial class ProtectionGroupInfo :  IEquatable<ProtectionGroupInfo>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets ProtectionStatus
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProtectionStatusEnum
        {
            
            /// <summary>
            /// Enum ACTIVE for "ACTIVE"
            /// </summary>
            [EnumMember(Value = "ACTIVE")]
            ACTIVE,
            
            /// <summary>
            /// Enum HALTED for "HALTED"
            /// </summary>
            [EnumMember(Value = "HALTED")]
            HALTED,
            
            /// <summary>
            /// Enum RECOVERED for "RECOVERED"
            /// </summary>
            [EnumMember(Value = "RECOVERED")]
            RECOVERED,
            
            /// <summary>
            /// Enum INPROGRESS for "IN_PROGRESS"
            /// </summary>
            [EnumMember(Value = "IN_PROGRESS")]
            INPROGRESS,
            
            /// <summary>
            /// Enum FAILED for "FAILED"
            /// </summary>
            [EnumMember(Value = "FAILED")]
            FAILED
        }

        /// <summary>
        /// Gets or Sets ProtectionStatus
        /// </summary>
        [DataMember(Name="protectionStatus", EmitDefaultValue=false)]
        public ProtectionStatusEnum? ProtectionStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProtectionGroupInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProtectionGroupInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProtectionGroupInfo" /> class.
        /// </summary>
        /// <param name="Er">Er (required).</param>
        /// <param name="Description">Description of the group.</param>
        /// <param name="PrimaryEr">PrimaryEr (required).</param>
        /// <param name="Members">Members.</param>
        /// <param name="Schedule">A Map from Replication Cluster Id to the schedule (required).</param>
        /// <param name="ProtectionStatus">ProtectionStatus (required).</param>
        /// <param name="Ex">Ex.</param>
        public ProtectionGroupInfo(EntityRef Er = default(EntityRef), string Description = default(string), EntityRef PrimaryEr = default(EntityRef), List<ProtectedVMInfo> Members = default(List<ProtectedVMInfo>), List<ReplicationClusterErToSchedule> Schedule = default(List<ReplicationClusterErToSchedule>), ProtectionStatusEnum? ProtectionStatus = default(ProtectionStatusEnum?), ErrorStack Ex = default(ErrorStack))
        {
            // to ensure "Er" is required (not null)
            if (Er == null)
            {
                throw new InvalidDataException("Er is a required property for ProtectionGroupInfo and cannot be null");
            }
            else
            {
                this.Er = Er;
            }
            // to ensure "PrimaryEr" is required (not null)
            if (PrimaryEr == null)
            {
                throw new InvalidDataException("PrimaryEr is a required property for ProtectionGroupInfo and cannot be null");
            }
            else
            {
                this.PrimaryEr = PrimaryEr;
            }
            // to ensure "Schedule" is required (not null)
            if (Schedule == null)
            {
                throw new InvalidDataException("Schedule is a required property for ProtectionGroupInfo and cannot be null");
            }
            else
            {
                this.Schedule = Schedule;
            }
            // to ensure "ProtectionStatus" is required (not null)
            if (ProtectionStatus == null)
            {
                throw new InvalidDataException("ProtectionStatus is a required property for ProtectionGroupInfo and cannot be null");
            }
            else
            {
                this.ProtectionStatus = ProtectionStatus;
            }
            this.Description = Description;
            this.Members = Members;
            this.Ex = Ex;
        }
        
        /// <summary>
        /// Gets or Sets Er
        /// </summary>
        [DataMember(Name="er", EmitDefaultValue=false)]
        public EntityRef Er { get; set; }

        /// <summary>
        /// Description of the group
        /// </summary>
        /// <value>Description of the group</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets PrimaryEr
        /// </summary>
        [DataMember(Name="primaryEr", EmitDefaultValue=false)]
        public EntityRef PrimaryEr { get; set; }

        /// <summary>
        /// Gets or Sets Members
        /// </summary>
        [DataMember(Name="members", EmitDefaultValue=false)]
        public List<ProtectedVMInfo> Members { get; set; }

        /// <summary>
        /// A Map from Replication Cluster Id to the schedule
        /// </summary>
        /// <value>A Map from Replication Cluster Id to the schedule</value>
        [DataMember(Name="schedule", EmitDefaultValue=false)]
        public List<ReplicationClusterErToSchedule> Schedule { get; set; }


        /// <summary>
        /// Gets or Sets Ex
        /// </summary>
        [DataMember(Name="ex", EmitDefaultValue=false)]
        public ErrorStack Ex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProtectionGroupInfo {\n");
            sb.Append("  Er: ").Append(Er).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  PrimaryEr: ").Append(PrimaryEr).Append("\n");
            sb.Append("  Members: ").Append(Members).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  ProtectionStatus: ").Append(ProtectionStatus).Append("\n");
            sb.Append("  Ex: ").Append(Ex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ProtectionGroupInfo);
        }

        /// <summary>
        /// Returns true if ProtectionGroupInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of ProtectionGroupInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProtectionGroupInfo other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Er == other.Er ||
                    this.Er != null &&
                    this.Er.Equals(other.Er)
                ) && 
                (
                    this.Description == other.Description ||
                    this.Description != null &&
                    this.Description.Equals(other.Description)
                ) && 
                (
                    this.PrimaryEr == other.PrimaryEr ||
                    this.PrimaryEr != null &&
                    this.PrimaryEr.Equals(other.PrimaryEr)
                ) && 
                (
                    this.Members == other.Members ||
                    this.Members != null &&
                    this.Members.SequenceEqual(other.Members)
                ) && 
                (
                    this.Schedule == other.Schedule ||
                    this.Schedule != null &&
                    this.Schedule.SequenceEqual(other.Schedule)
                ) && 
                (
                    this.ProtectionStatus == other.ProtectionStatus ||
                    this.ProtectionStatus != null &&
                    this.ProtectionStatus.Equals(other.ProtectionStatus)
                ) && 
                (
                    this.Ex == other.Ex ||
                    this.Ex != null &&
                    this.Ex.Equals(other.Ex)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Er != null)
                    hash = hash * 59 + this.Er.GetHashCode();
                if (this.Description != null)
                    hash = hash * 59 + this.Description.GetHashCode();
                if (this.PrimaryEr != null)
                    hash = hash * 59 + this.PrimaryEr.GetHashCode();
                if (this.Members != null)
                    hash = hash * 59 + this.Members.GetHashCode();
                if (this.Schedule != null)
                    hash = hash * 59 + this.Schedule.GetHashCode();
                if (this.ProtectionStatus != null)
                    hash = hash * 59 + this.ProtectionStatus.GetHashCode();
                if (this.Ex != null)
                    hash = hash * 59 + this.Ex.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
