/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ProtectedVMInfo
    /// </summary>
    [DataContract]
    public partial class ProtectedVMInfo :  IEquatable<ProtectedVMInfo>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets ProtectionStatus
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProtectionStatusEnum
        {
            
            /// <summary>
            /// Enum ACTIVE for "ACTIVE"
            /// </summary>
            [EnumMember(Value = "ACTIVE")]
            ACTIVE,
            
            /// <summary>
            /// Enum HALTED for "HALTED"
            /// </summary>
            [EnumMember(Value = "HALTED")]
            HALTED,
            
            /// <summary>
            /// Enum RECOVERED for "RECOVERED"
            /// </summary>
            [EnumMember(Value = "RECOVERED")]
            RECOVERED,
            
            /// <summary>
            /// Enum INPROGRESS for "IN_PROGRESS"
            /// </summary>
            [EnumMember(Value = "IN_PROGRESS")]
            INPROGRESS,
            
            /// <summary>
            /// Enum FAILED for "FAILED"
            /// </summary>
            [EnumMember(Value = "FAILED")]
            FAILED
        }

        /// <summary>
        /// Gets or Sets ProtectionStatus
        /// </summary>
        [DataMember(Name="protectionStatus", EmitDefaultValue=false)]
        public ProtectionStatusEnum? ProtectionStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProtectedVMInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProtectedVMInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProtectedVMInfo" /> class.
        /// </summary>
        /// <param name="Er">Er (required).</param>
        /// <param name="ClusterEr">ClusterEr (required).</param>
        /// <param name="Schedule">A Map from Replication Cluster Id to the schedule additional properties - ReplicationSchedule (required).</param>
        /// <param name="ProtectionStatus">ProtectionStatus (required).</param>
        /// <param name="ProtectionInfo">ProtectionInfo.</param>
        /// <param name="Ex">Ex.</param>
        public ProtectedVMInfo(EntityRef Er = default(EntityRef), EntityRef ClusterEr = default(EntityRef), List<ReplicationClusterErToSchedule> Schedule = default(List<ReplicationClusterErToSchedule>), ProtectionStatusEnum? ProtectionStatus = default(ProtectionStatusEnum?), ProtectionInfo ProtectionInfo = default(ProtectionInfo), ErrorStack Ex = default(ErrorStack))
        {
            // to ensure "Er" is required (not null)
            if (Er == null)
            {
                throw new InvalidDataException("Er is a required property for ProtectedVMInfo and cannot be null");
            }
            else
            {
                this.Er = Er;
            }
            // to ensure "ClusterEr" is required (not null)
            if (ClusterEr == null)
            {
                throw new InvalidDataException("ClusterEr is a required property for ProtectedVMInfo and cannot be null");
            }
            else
            {
                this.ClusterEr = ClusterEr;
            }
            // to ensure "Schedule" is required (not null)
            if (Schedule == null)
            {
                throw new InvalidDataException("Schedule is a required property for ProtectedVMInfo and cannot be null");
            }
            else
            {
                this.Schedule = Schedule;
            }
            // to ensure "ProtectionStatus" is required (not null)
            if (ProtectionStatus == null)
            {
                throw new InvalidDataException("ProtectionStatus is a required property for ProtectedVMInfo and cannot be null");
            }
            else
            {
                this.ProtectionStatus = ProtectionStatus;
            }
            this.ProtectionInfo = ProtectionInfo;
            this.Ex = Ex;
        }
        
        /// <summary>
        /// Gets or Sets Er
        /// </summary>
        [DataMember(Name="er", EmitDefaultValue=false)]
        public EntityRef Er { get; set; }

        /// <summary>
        /// Gets or Sets ClusterEr
        /// </summary>
        [DataMember(Name="clusterEr", EmitDefaultValue=false)]
        public EntityRef ClusterEr { get; set; }

        /// <summary>
        /// A Map from Replication Cluster Id to the schedule additional properties - ReplicationSchedule
        /// </summary>
        /// <value>A Map from Replication Cluster Id to the schedule additional properties - ReplicationSchedule</value>
        [DataMember(Name="schedule", EmitDefaultValue=false)]
        public List<ReplicationClusterErToSchedule> Schedule { get; set; }


        /// <summary>
        /// Gets or Sets ProtectionInfo
        /// </summary>
        [DataMember(Name="protectionInfo", EmitDefaultValue=false)]
        public ProtectionInfo ProtectionInfo { get; set; }

        /// <summary>
        /// Gets or Sets Ex
        /// </summary>
        [DataMember(Name="ex", EmitDefaultValue=false)]
        public ErrorStack Ex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProtectedVMInfo {\n");
            sb.Append("  Er: ").Append(Er).Append("\n");
            sb.Append("  ClusterEr: ").Append(ClusterEr).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  ProtectionStatus: ").Append(ProtectionStatus).Append("\n");
            sb.Append("  ProtectionInfo: ").Append(ProtectionInfo).Append("\n");
            sb.Append("  Ex: ").Append(Ex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ProtectedVMInfo);
        }

        /// <summary>
        /// Returns true if ProtectedVMInfo instances are equal
        /// </summary>
        /// <param name="other">Instance of ProtectedVMInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProtectedVMInfo other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Er == other.Er ||
                    this.Er != null &&
                    this.Er.Equals(other.Er)
                ) && 
                (
                    this.ClusterEr == other.ClusterEr ||
                    this.ClusterEr != null &&
                    this.ClusterEr.Equals(other.ClusterEr)
                ) && 
                (
                    this.Schedule == other.Schedule ||
                    this.Schedule != null &&
                    this.Schedule.SequenceEqual(other.Schedule)
                ) && 
                (
                    this.ProtectionStatus == other.ProtectionStatus ||
                    this.ProtectionStatus != null &&
                    this.ProtectionStatus.Equals(other.ProtectionStatus)
                ) && 
                (
                    this.ProtectionInfo == other.ProtectionInfo ||
                    this.ProtectionInfo != null &&
                    this.ProtectionInfo.Equals(other.ProtectionInfo)
                ) && 
                (
                    this.Ex == other.Ex ||
                    this.Ex != null &&
                    this.Ex.Equals(other.Ex)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Er != null)
                    hash = hash * 59 + this.Er.GetHashCode();
                if (this.ClusterEr != null)
                    hash = hash * 59 + this.ClusterEr.GetHashCode();
                if (this.Schedule != null)
                    hash = hash * 59 + this.Schedule.GetHashCode();
                if (this.ProtectionStatus != null)
                    hash = hash * 59 + this.ProtectionStatus.GetHashCode();
                if (this.ProtectionInfo != null)
                    hash = hash * 59 + this.ProtectionInfo.GetHashCode();
                if (this.Ex != null)
                    hash = hash * 59 + this.Ex.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
