/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// A map from Replication Cluster Er to the schedule
    /// </summary>
    [DataContract]
    public partial class ReplicationClusterErToSchedule :  IEquatable<ReplicationClusterErToSchedule>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplicationClusterErToSchedule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReplicationClusterErToSchedule() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplicationClusterErToSchedule" /> class.
        /// </summary>
        /// <param name="TargetClusterEr">TargetClusterEr (required).</param>
        /// <param name="Schedule">Schedule (required).</param>
        public ReplicationClusterErToSchedule(EntityRef TargetClusterEr = default(EntityRef), ReplicationSchedule Schedule = default(ReplicationSchedule))
        {
            // to ensure "TargetClusterEr" is required (not null)
            if (TargetClusterEr == null)
            {
                throw new InvalidDataException("TargetClusterEr is a required property for ReplicationClusterErToSchedule and cannot be null");
            }
            else
            {
                this.TargetClusterEr = TargetClusterEr;
            }
            // to ensure "Schedule" is required (not null)
            if (Schedule == null)
            {
                throw new InvalidDataException("Schedule is a required property for ReplicationClusterErToSchedule and cannot be null");
            }
            else
            {
                this.Schedule = Schedule;
            }
        }
        
        /// <summary>
        /// Gets or Sets TargetClusterEr
        /// </summary>
        [DataMember(Name="targetClusterEr", EmitDefaultValue=false)]
        public EntityRef TargetClusterEr { get; set; }

        /// <summary>
        /// Gets or Sets Schedule
        /// </summary>
        [DataMember(Name="schedule", EmitDefaultValue=false)]
        public ReplicationSchedule Schedule { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReplicationClusterErToSchedule {\n");
            sb.Append("  TargetClusterEr: ").Append(TargetClusterEr).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ReplicationClusterErToSchedule);
        }

        /// <summary>
        /// Returns true if ReplicationClusterErToSchedule instances are equal
        /// </summary>
        /// <param name="other">Instance of ReplicationClusterErToSchedule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReplicationClusterErToSchedule other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.TargetClusterEr == other.TargetClusterEr ||
                    this.TargetClusterEr != null &&
                    this.TargetClusterEr.Equals(other.TargetClusterEr)
                ) && 
                (
                    this.Schedule == other.Schedule ||
                    this.Schedule != null &&
                    this.Schedule.Equals(other.Schedule)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.TargetClusterEr != null)
                    hash = hash * 59 + this.TargetClusterEr.GetHashCode();
                if (this.Schedule != null)
                    hash = hash * 59 + this.Schedule.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
