/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AboutInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AboutInfoTests
    {
        // TODO uncomment below to declare an instance variable for AboutInfo
        //private AboutInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AboutInfo
            //instance = new AboutInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AboutInfo
        /// </summary>
        [Test]
        public void AboutInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AboutInfo
            //Assert.IsInstanceOfType<AboutInfo> (instance, "variable 'instance' is a AboutInfo");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Build'
        /// </summary>
        [Test]
        public void BuildTest()
        {
            // TODO unit test for the property 'Build'
        }
        /// <summary>
        /// Test the property 'DisplayVersion'
        /// </summary>
        [Test]
        public void DisplayVersionTest()
        {
            // TODO unit test for the property 'DisplayVersion'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'InstanceUuid'
        /// </summary>
        [Test]
        public void InstanceUuidTest()
        {
            // TODO unit test for the property 'InstanceUuid'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Test]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
        /// <summary>
        /// Test the property 'ModelNumber'
        /// </summary>
        [Test]
        public void ModelNumberTest()
        {
            // TODO unit test for the property 'ModelNumber'
        }
        /// <summary>
        /// Test the property 'ServiceType'
        /// </summary>
        [Test]
        public void ServiceTypeTest()
        {
            // TODO unit test for the property 'ServiceType'
        }
        /// <summary>
        /// Test the property 'Pid'
        /// </summary>
        [Test]
        public void PidTest()
        {
            // TODO unit test for the property 'Pid'
        }
        /// <summary>
        /// Test the property 'ProductVersion'
        /// </summary>
        [Test]
        public void ProductVersionTest()
        {
            // TODO unit test for the property 'ProductVersion'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'ApiVersion'
        /// </summary>
        [Test]
        public void ApiVersionTest()
        {
            // TODO unit test for the property 'ApiVersion'
        }

    }

}
