/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DisplayReplicationDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DisplayReplicationDetailsTests
    {
        // TODO uncomment below to declare an instance variable for DisplayReplicationDetails
        //private DisplayReplicationDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DisplayReplicationDetails
            //instance = new DisplayReplicationDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DisplayReplicationDetails
        /// </summary>
        [Test]
        public void DisplayReplicationDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DisplayReplicationDetails
            //Assert.IsInstanceOfType<DisplayReplicationDetails> (instance, "variable 'instance' is a DisplayReplicationDetails");
        }

        /// <summary>
        /// Test the property 'VmName'
        /// </summary>
        [Test]
        public void VmNameTest()
        {
            // TODO unit test for the property 'VmName'
        }
        /// <summary>
        /// Test the property 'RemoteClusterName'
        /// </summary>
        [Test]
        public void RemoteClusterNameTest()
        {
            // TODO unit test for the property 'RemoteClusterName'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'ProtectionGroup'
        /// </summary>
        [Test]
        public void ProtectionGroupTest()
        {
            // TODO unit test for the property 'ProtectionGroup'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'DataTransferred'
        /// </summary>
        [Test]
        public void DataTransferredTest()
        {
            // TODO unit test for the property 'DataTransferred'
        }
        /// <summary>
        /// Test the property 'PrecentTransferred'
        /// </summary>
        [Test]
        public void PrecentTransferredTest()
        {
            // TODO unit test for the property 'PrecentTransferred'
        }

    }

}
