/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DvsDeviceNetworkMap
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DvsDeviceNetworkMapTests
    {
        // TODO uncomment below to declare an instance variable for DvsDeviceNetworkMap
        //private DvsDeviceNetworkMap instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DvsDeviceNetworkMap
            //instance = new DvsDeviceNetworkMap();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DvsDeviceNetworkMap
        /// </summary>
        [Test]
        public void DvsDeviceNetworkMapInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DvsDeviceNetworkMap
            //Assert.IsInstanceOfType<DvsDeviceNetworkMap> (instance, "variable 'instance' is a DvsDeviceNetworkMap");
        }

        /// <summary>
        /// Test the property 'Devicekey'
        /// </summary>
        [Test]
        public void DevicekeyTest()
        {
            // TODO unit test for the property 'Devicekey'
        }
        /// <summary>
        /// Test the property 'Dvsportgroupname'
        /// </summary>
        [Test]
        public void DvsportgroupnameTest()
        {
            // TODO unit test for the property 'Dvsportgroupname'
        }

    }

}
