/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GroupEditParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupEditParamsTests
    {
        // TODO uncomment below to declare an instance variable for GroupEditParams
        //private GroupEditParams instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupEditParams
            //instance = new GroupEditParams();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupEditParams
        /// </summary>
        [Test]
        public void GroupEditParamsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupEditParams
            //Assert.IsInstanceOfType<GroupEditParams> (instance, "variable 'instance' is a GroupEditParams");
        }

        /// <summary>
        /// Test the property 'VmsToAdd'
        /// </summary>
        [Test]
        public void VmsToAddTest()
        {
            // TODO unit test for the property 'VmsToAdd'
        }
        /// <summary>
        /// Test the property 'VmsToRemove'
        /// </summary>
        [Test]
        public void VmsToRemoveTest()
        {
            // TODO unit test for the property 'VmsToRemove'
        }
        /// <summary>
        /// Test the property 'Rename'
        /// </summary>
        [Test]
        public void RenameTest()
        {
            // TODO unit test for the property 'Rename'
        }

    }

}
