/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IpPoolInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IpPoolInfoTests
    {
        // TODO uncomment below to declare an instance variable for IpPoolInfo
        //private IpPoolInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IpPoolInfo
            //instance = new IpPoolInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IpPoolInfo
        /// </summary>
        [Test]
        public void IpPoolInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IpPoolInfo
            //Assert.IsInstanceOfType<IpPoolInfo> (instance, "variable 'instance' is a IpPoolInfo");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IpRanges'
        /// </summary>
        [Test]
        public void IpRangesTest()
        {
            // TODO unit test for the property 'IpRanges'
        }
        /// <summary>
        /// Test the property 'UsedIpRanges'
        /// </summary>
        [Test]
        public void UsedIpRangesTest()
        {
            // TODO unit test for the property 'UsedIpRanges'
        }
        /// <summary>
        /// Test the property 'Subnet'
        /// </summary>
        [Test]
        public void SubnetTest()
        {
            // TODO unit test for the property 'Subnet'
        }
        /// <summary>
        /// Test the property 'Gateway'
        /// </summary>
        [Test]
        public void GatewayTest()
        {
            // TODO unit test for the property 'Gateway'
        }

    }

}
