/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Job
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JobTests
    {
        // TODO uncomment below to declare an instance variable for Job
        //private Job instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Job
            //instance = new Job();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Job
        /// </summary>
        [Test]
        public void JobInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Job
            //Assert.IsInstanceOfType<Job> (instance, "variable 'instance' is a Job");
        }

        /// <summary>
        /// Test the property 'Jobid'
        /// </summary>
        [Test]
        public void JobidTest()
        {
            // TODO unit test for the property 'Jobid'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'TimeSubmittedMillis'
        /// </summary>
        [Test]
        public void TimeSubmittedMillisTest()
        {
            // TODO unit test for the property 'TimeSubmittedMillis'
        }
        /// <summary>
        /// Test the property 'TimeStartedMillis'
        /// </summary>
        [Test]
        public void TimeStartedMillisTest()
        {
            // TODO unit test for the property 'TimeStartedMillis'
        }
        /// <summary>
        /// Test the property 'TimeElapsedMillis'
        /// </summary>
        [Test]
        public void TimeElapsedMillisTest()
        {
            // TODO unit test for the property 'TimeElapsedMillis'
        }
        /// <summary>
        /// Test the property 'OutParameters'
        /// </summary>
        [Test]
        public void OutParametersTest()
        {
            // TODO unit test for the property 'OutParameters'
        }
        /// <summary>
        /// Test the property 'JobSteps'
        /// </summary>
        [Test]
        public void JobStepsTest()
        {
            // TODO unit test for the property 'JobSteps'
        }
        /// <summary>
        /// Test the property 'SuspendOnExit'
        /// </summary>
        [Test]
        public void SuspendOnExitTest()
        {
            // TODO unit test for the property 'SuspendOnExit'
        }
        /// <summary>
        /// Test the property 'MethodName'
        /// </summary>
        [Test]
        public void MethodNameTest()
        {
            // TODO unit test for the property 'MethodName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'IsCancelRequested'
        /// </summary>
        [Test]
        public void IsCancelRequestedTest()
        {
            // TODO unit test for the property 'IsCancelRequested'
        }
        /// <summary>
        /// Test the property 'IsCanceled'
        /// </summary>
        [Test]
        public void IsCanceledTest()
        {
            // TODO unit test for the property 'IsCanceled'
        }
        /// <summary>
        /// Test the property 'PercentComplete'
        /// </summary>
        [Test]
        public void PercentCompleteTest()
        {
            // TODO unit test for the property 'PercentComplete'
        }
        /// <summary>
        /// Test the property 'LifetimeAfterExitMillis'
        /// </summary>
        [Test]
        public void LifetimeAfterExitMillisTest()
        {
            // TODO unit test for the property 'LifetimeAfterExitMillis'
        }
        /// <summary>
        /// Test the property 'SummaryStepState'
        /// </summary>
        [Test]
        public void SummaryStepStateTest()
        {
            // TODO unit test for the property 'SummaryStepState'
        }
        /// <summary>
        /// Test the property 'LcDescription'
        /// </summary>
        [Test]
        public void LcDescriptionTest()
        {
            // TODO unit test for the property 'LcDescription'
        }
        /// <summary>
        /// Test the property 'LcMessage'
        /// </summary>
        [Test]
        public void LcMessageTest()
        {
            // TODO unit test for the property 'LcMessage'
        }

    }

}
