/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LocalizableMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LocalizableMessageTests
    {
        // TODO uncomment below to declare an instance variable for LocalizableMessage
        //private LocalizableMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LocalizableMessage
            //instance = new LocalizableMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LocalizableMessage
        /// </summary>
        [Test]
        public void LocalizableMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LocalizableMessage
            //Assert.IsInstanceOfType<LocalizableMessage> (instance, "variable 'instance' is a LocalizableMessage");
        }

        /// <summary>
        /// Test the property 'Msgid'
        /// </summary>
        [Test]
        public void MsgidTest()
        {
            // TODO unit test for the property 'Msgid'
        }
        /// <summary>
        /// Test the property 'MsgidPlural'
        /// </summary>
        [Test]
        public void MsgidPluralTest()
        {
            // TODO unit test for the property 'MsgidPlural'
        }
        /// <summary>
        /// Test the property 'Msgctxt'
        /// </summary>
        [Test]
        public void MsgctxtTest()
        {
            // TODO unit test for the property 'Msgctxt'
        }
        /// <summary>
        /// Test the property 'Msgstr'
        /// </summary>
        [Test]
        public void MsgstrTest()
        {
            // TODO unit test for the property 'Msgstr'
        }
        /// <summary>
        /// Test the property '_Params'
        /// </summary>
        [Test]
        public void _ParamsTest()
        {
            // TODO unit test for the property '_Params'
        }

    }

}
