/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MapPortTypeToPortNumber
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MapPortTypeToPortNumberTests
    {
        // TODO uncomment below to declare an instance variable for MapPortTypeToPortNumber
        //private MapPortTypeToPortNumber instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MapPortTypeToPortNumber
            //instance = new MapPortTypeToPortNumber();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MapPortTypeToPortNumber
        /// </summary>
        [Test]
        public void MapPortTypeToPortNumberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MapPortTypeToPortNumber
            //Assert.IsInstanceOfType<MapPortTypeToPortNumber> (instance, "variable 'instance' is a MapPortTypeToPortNumber");
        }

        /// <summary>
        /// Test the property '_String'
        /// </summary>
        [Test]
        public void _StringTest()
        {
            // TODO unit test for the property '_String'
        }
        /// <summary>
        /// Test the property 'I16'
        /// </summary>
        [Test]
        public void I16Test()
        {
            // TODO unit test for the property 'I16'
        }

    }

}
