/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MapPairErToReplicationPeerInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MapPairErToReplicationPeerInfoTests
    {
        // TODO uncomment below to declare an instance variable for MapPairErToReplicationPeerInfo
        //private MapPairErToReplicationPeerInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MapPairErToReplicationPeerInfo
            //instance = new MapPairErToReplicationPeerInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MapPairErToReplicationPeerInfo
        /// </summary>
        [Test]
        public void MapPairErToReplicationPeerInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MapPairErToReplicationPeerInfo
            //Assert.IsInstanceOfType<MapPairErToReplicationPeerInfo> (instance, "variable 'instance' is a MapPairErToReplicationPeerInfo");
        }

        /// <summary>
        /// Test the property 'Er'
        /// </summary>
        [Test]
        public void ErTest()
        {
            // TODO unit test for the property 'Er'
        }
        /// <summary>
        /// Test the property 'PeerInfo'
        /// </summary>
        [Test]
        public void PeerInfoTest()
        {
            // TODO unit test for the property 'PeerInfo'
        }

    }

}
