/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProtectedVMSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProtectedVMSpecTests
    {
        // TODO uncomment below to declare an instance variable for ProtectedVMSpec
        //private ProtectedVMSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProtectedVMSpec
            //instance = new ProtectedVMSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProtectedVMSpec
        /// </summary>
        [Test]
        public void ProtectedVMSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtectedVMSpec
            //Assert.IsInstanceOfType<ProtectedVMSpec> (instance, "variable 'instance' is a ProtectedVMSpec");
        }

        /// <summary>
        /// Test the property 'VmEr'
        /// </summary>
        [Test]
        public void VmErTest()
        {
            // TODO unit test for the property 'VmEr'
        }
        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Test]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }

    }

}
