/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProtectionGroupInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProtectionGroupInfoTests
    {
        // TODO uncomment below to declare an instance variable for ProtectionGroupInfo
        //private ProtectionGroupInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProtectionGroupInfo
            //instance = new ProtectionGroupInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProtectionGroupInfo
        /// </summary>
        [Test]
        public void ProtectionGroupInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtectionGroupInfo
            //Assert.IsInstanceOfType<ProtectionGroupInfo> (instance, "variable 'instance' is a ProtectionGroupInfo");
        }

        /// <summary>
        /// Test the property 'Er'
        /// </summary>
        [Test]
        public void ErTest()
        {
            // TODO unit test for the property 'Er'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PrimaryEr'
        /// </summary>
        [Test]
        public void PrimaryErTest()
        {
            // TODO unit test for the property 'PrimaryEr'
        }
        /// <summary>
        /// Test the property 'Members'
        /// </summary>
        [Test]
        public void MembersTest()
        {
            // TODO unit test for the property 'Members'
        }
        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Test]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }
        /// <summary>
        /// Test the property 'ProtectionStatus'
        /// </summary>
        [Test]
        public void ProtectionStatusTest()
        {
            // TODO unit test for the property 'ProtectionStatus'
        }
        /// <summary>
        /// Test the property 'Ex'
        /// </summary>
        [Test]
        public void ExTest()
        {
            // TODO unit test for the property 'Ex'
        }

    }

}
