/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProtectedVMInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProtectedVMInfoTests
    {
        // TODO uncomment below to declare an instance variable for ProtectedVMInfo
        //private ProtectedVMInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProtectedVMInfo
            //instance = new ProtectedVMInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProtectedVMInfo
        /// </summary>
        [Test]
        public void ProtectedVMInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProtectedVMInfo
            //Assert.IsInstanceOfType<ProtectedVMInfo> (instance, "variable 'instance' is a ProtectedVMInfo");
        }

        /// <summary>
        /// Test the property 'Er'
        /// </summary>
        [Test]
        public void ErTest()
        {
            // TODO unit test for the property 'Er'
        }
        /// <summary>
        /// Test the property 'ClusterEr'
        /// </summary>
        [Test]
        public void ClusterErTest()
        {
            // TODO unit test for the property 'ClusterEr'
        }
        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Test]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }
        /// <summary>
        /// Test the property 'ProtectionStatus'
        /// </summary>
        [Test]
        public void ProtectionStatusTest()
        {
            // TODO unit test for the property 'ProtectionStatus'
        }
        /// <summary>
        /// Test the property 'ProtectionInfo'
        /// </summary>
        [Test]
        public void ProtectionInfoTest()
        {
            // TODO unit test for the property 'ProtectionInfo'
        }
        /// <summary>
        /// Test the property 'Ex'
        /// </summary>
        [Test]
        public void ExTest()
        {
            // TODO unit test for the property 'Ex'
        }

    }

}
