/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RecoverVmOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecoverVmOptionsTests
    {
        // TODO uncomment below to declare an instance variable for RecoverVmOptions
        //private RecoverVmOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecoverVmOptions
            //instance = new RecoverVmOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecoverVmOptions
        /// </summary>
        [Test]
        public void RecoverVmOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecoverVmOptions
            //Assert.IsInstanceOfType<RecoverVmOptions> (instance, "variable 'instance' is a RecoverVmOptions");
        }

        /// <summary>
        /// Test the property 'ResourcePoolEr'
        /// </summary>
        [Test]
        public void ResourcePoolErTest()
        {
            // TODO unit test for the property 'ResourcePoolEr'
        }
        /// <summary>
        /// Test the property 'FolderEr'
        /// </summary>
        [Test]
        public void FolderErTest()
        {
            // TODO unit test for the property 'FolderEr'
        }
        /// <summary>
        /// Test the property 'TestNetwork'
        /// </summary>
        [Test]
        public void TestNetworkTest()
        {
            // TODO unit test for the property 'TestNetwork'
        }
        /// <summary>
        /// Test the property 'PowerOn'
        /// </summary>
        [Test]
        public void PowerOnTest()
        {
            // TODO unit test for the property 'PowerOn'
        }
        /// <summary>
        /// Test the property 'NetworkMap'
        /// </summary>
        [Test]
        public void NetworkMapTest()
        {
            // TODO unit test for the property 'NetworkMap'
        }
        /// <summary>
        /// Test the property 'NewName'
        /// </summary>
        [Test]
        public void NewNameTest()
        {
            // TODO unit test for the property 'NewName'
        }

    }

}
