/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReplicationSchedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReplicationScheduleTests
    {
        // TODO uncomment below to declare an instance variable for ReplicationSchedule
        //private ReplicationSchedule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplicationSchedule
            //instance = new ReplicationSchedule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplicationSchedule
        /// </summary>
        [Test]
        public void ReplicationScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReplicationSchedule
            //Assert.IsInstanceOfType<ReplicationSchedule> (instance, "variable 'instance' is a ReplicationSchedule");
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'IntervalInMinutes'
        /// </summary>
        [Test]
        public void IntervalInMinutesTest()
        {
            // TODO unit test for the property 'IntervalInMinutes'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'QuiesceType'
        /// </summary>
        [Test]
        public void QuiesceTypeTest()
        {
            // TODO unit test for the property 'QuiesceType'
        }

    }

}
