/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReplicationPlatDatastore
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReplicationPlatDatastoreTests
    {
        // TODO uncomment below to declare an instance variable for ReplicationPlatDatastore
        //private ReplicationPlatDatastore instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplicationPlatDatastore
            //instance = new ReplicationPlatDatastore();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplicationPlatDatastore
        /// </summary>
        [Test]
        public void ReplicationPlatDatastoreInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReplicationPlatDatastore
            //Assert.IsInstanceOfType<ReplicationPlatDatastore> (instance, "variable 'instance' is a ReplicationPlatDatastore");
        }

        /// <summary>
        /// Test the property 'ClusterEr'
        /// </summary>
        [Test]
        public void ClusterErTest()
        {
            // TODO unit test for the property 'ClusterEr'
        }
        /// <summary>
        /// Test the property 'DatastoreEr'
        /// </summary>
        [Test]
        public void DatastoreErTest()
        {
            // TODO unit test for the property 'DatastoreEr'
        }

    }

}
