/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReplicationDatastore
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReplicationDatastoreTests
    {
        // TODO uncomment below to declare an instance variable for ReplicationDatastore
        //private ReplicationDatastore instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplicationDatastore
            //instance = new ReplicationDatastore();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplicationDatastore
        /// </summary>
        [Test]
        public void ReplicationDatastoreInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReplicationDatastore
            //Assert.IsInstanceOfType<ReplicationDatastore> (instance, "variable 'instance' is a ReplicationDatastore");
        }

        /// <summary>
        /// Test the property 'ClusterEr'
        /// </summary>
        [Test]
        public void ClusterErTest()
        {
            // TODO unit test for the property 'ClusterEr'
        }
        /// <summary>
        /// Test the property 'DatastoreEr'
        /// </summary>
        [Test]
        public void DatastoreErTest()
        {
            // TODO unit test for the property 'DatastoreEr'
        }
        /// <summary>
        /// Test the property 'VirtDatastoreEr'
        /// </summary>
        [Test]
        public void VirtDatastoreErTest()
        {
            // TODO unit test for the property 'VirtDatastoreEr'
        }
        /// <summary>
        /// Test the property 'TotalCapacity'
        /// </summary>
        [Test]
        public void TotalCapacityTest()
        {
            // TODO unit test for the property 'TotalCapacity'
        }
        /// <summary>
        /// Test the property 'FreeCapacity'
        /// </summary>
        [Test]
        public void FreeCapacityTest()
        {
            // TODO unit test for the property 'FreeCapacity'
        }

    }

}
