/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReplicationPeerInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReplicationPeerInfoTests
    {
        // TODO uncomment below to declare an instance variable for ReplicationPeerInfo
        //private ReplicationPeerInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplicationPeerInfo
            //instance = new ReplicationPeerInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplicationPeerInfo
        /// </summary>
        [Test]
        public void ReplicationPeerInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReplicationPeerInfo
            //Assert.IsInstanceOfType<ReplicationPeerInfo> (instance, "variable 'instance' is a ReplicationPeerInfo");
        }

        /// <summary>
        /// Test the property 'Er'
        /// </summary>
        [Test]
        public void ErTest()
        {
            // TODO unit test for the property 'Er'
        }
        /// <summary>
        /// Test the property 'Mcip'
        /// </summary>
        [Test]
        public void McipTest()
        {
            // TODO unit test for the property 'Mcip'
        }
        /// <summary>
        /// Test the property 'Dcip'
        /// </summary>
        [Test]
        public void DcipTest()
        {
            // TODO unit test for the property 'Dcip'
        }
        /// <summary>
        /// Test the property 'ReplCip'
        /// </summary>
        [Test]
        public void ReplCipTest()
        {
            // TODO unit test for the property 'ReplCip'
        }
        /// <summary>
        /// Test the property 'Ports'
        /// </summary>
        [Test]
        public void PortsTest()
        {
            // TODO unit test for the property 'Ports'
        }
        /// <summary>
        /// Test the property 'Datastores'
        /// </summary>
        [Test]
        public void DatastoresTest()
        {
            // TODO unit test for the property 'Datastores'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDetails'
        /// </summary>
        [Test]
        public void StatusDetailsTest()
        {
            // TODO unit test for the property 'StatusDetails'
        }

    }

}
