/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReplicationNetwork
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReplicationNetworkTests
    {
        // TODO uncomment below to declare an instance variable for ReplicationNetwork
        //private ReplicationNetwork instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplicationNetwork
            //instance = new ReplicationNetwork();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplicationNetwork
        /// </summary>
        [Test]
        public void ReplicationNetworkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReplicationNetwork
            //Assert.IsInstanceOfType<ReplicationNetwork> (instance, "variable 'instance' is a ReplicationNetwork");
        }

        /// <summary>
        /// Test the property 'NetworkName'
        /// </summary>
        [Test]
        public void NetworkNameTest()
        {
            // TODO unit test for the property 'NetworkName'
        }
        /// <summary>
        /// Test the property 'Subnet'
        /// </summary>
        [Test]
        public void SubnetTest()
        {
            // TODO unit test for the property 'Subnet'
        }
        /// <summary>
        /// Test the property 'IpRanges'
        /// </summary>
        [Test]
        public void IpRangesTest()
        {
            // TODO unit test for the property 'IpRanges'
        }
        /// <summary>
        /// Test the property 'Gateway'
        /// </summary>
        [Test]
        public void GatewayTest()
        {
            // TODO unit test for the property 'Gateway'
        }
        /// <summary>
        /// Test the property 'Vlanid'
        /// </summary>
        [Test]
        public void VlanidTest()
        {
            // TODO unit test for the property 'Vlanid'
        }
        /// <summary>
        /// Test the property 'Bandwidth'
        /// </summary>
        [Test]
        public void BandwidthTest()
        {
            // TODO unit test for the property 'Bandwidth'
        }
        /// <summary>
        /// Test the property 'UnusedIps'
        /// </summary>
        [Test]
        public void UnusedIpsTest()
        {
            // TODO unit test for the property 'UnusedIps'
        }
        /// <summary>
        /// Test the property 'UsedIps'
        /// </summary>
        [Test]
        public void UsedIpsTest()
        {
            // TODO unit test for the property 'UsedIps'
        }
        /// <summary>
        /// Test the property 'VlanReplication'
        /// </summary>
        [Test]
        public void VlanReplicationTest()
        {
            // TODO unit test for the property 'VlanReplication'
        }

    }

}
