/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReplicationPeerSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReplicationPeerSpecTests
    {
        // TODO uncomment below to declare an instance variable for ReplicationPeerSpec
        //private ReplicationPeerSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplicationPeerSpec
            //instance = new ReplicationPeerSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplicationPeerSpec
        /// </summary>
        [Test]
        public void ReplicationPeerSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReplicationPeerSpec
            //Assert.IsInstanceOfType<ReplicationPeerSpec> (instance, "variable 'instance' is a ReplicationPeerSpec");
        }

        /// <summary>
        /// Test the property 'MgmtIp'
        /// </summary>
        [Test]
        public void MgmtIpTest()
        {
            // TODO unit test for the property 'MgmtIp'
        }
        /// <summary>
        /// Test the property 'Cred'
        /// </summary>
        [Test]
        public void CredTest()
        {
            // TODO unit test for the property 'Cred'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
