/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReplicationStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReplicationStatusTests
    {
        // TODO uncomment below to declare an instance variable for ReplicationStatus
        //private ReplicationStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReplicationStatus
            //instance = new ReplicationStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReplicationStatus
        /// </summary>
        [Test]
        public void ReplicationStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReplicationStatus
            //Assert.IsInstanceOfType<ReplicationStatus> (instance, "variable 'instance' is a ReplicationStatus");
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'BytesReplicated'
        /// </summary>
        [Test]
        public void BytesReplicatedTest()
        {
            // TODO unit test for the property 'BytesReplicated'
        }
        /// <summary>
        /// Test the property 'PackEr'
        /// </summary>
        [Test]
        public void PackErTest()
        {
            // TODO unit test for the property 'PackEr'
        }
        /// <summary>
        /// Test the property 'PctComplete'
        /// </summary>
        [Test]
        public void PctCompleteTest()
        {
            // TODO unit test for the property 'PctComplete'
        }
        /// <summary>
        /// Test the property 'Ex'
        /// </summary>
        [Test]
        public void ExTest()
        {
            // TODO unit test for the property 'Ex'
        }
        /// <summary>
        /// Test the property 'RpoStatus'
        /// </summary>
        [Test]
        public void RpoStatusTest()
        {
            // TODO unit test for the property 'RpoStatus'
        }

    }

}
