/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RpoStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RpoStatusTests
    {
        // TODO uncomment below to declare an instance variable for RpoStatus
        //private RpoStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RpoStatus
            //instance = new RpoStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RpoStatus
        /// </summary>
        [Test]
        public void RpoStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RpoStatus
            //Assert.IsInstanceOfType<RpoStatus> (instance, "variable 'instance' is a RpoStatus");
        }

        /// <summary>
        /// Test the property 'RpoExceeded'
        /// </summary>
        [Test]
        public void RpoExceededTest()
        {
            // TODO unit test for the property 'RpoExceeded'
        }
        /// <summary>
        /// Test the property 'Expected'
        /// </summary>
        [Test]
        public void ExpectedTest()
        {
            // TODO unit test for the property 'Expected'
        }
        /// <summary>
        /// Test the property 'Actual'
        /// </summary>
        [Test]
        public void ActualTest()
        {
            // TODO unit test for the property 'Actual'
        }

    }

}
