/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VirtualMachine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VirtualMachineTests
    {
        // TODO uncomment below to declare an instance variable for VirtualMachine
        //private VirtualMachine instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VirtualMachine
            //instance = new VirtualMachine();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VirtualMachine
        /// </summary>
        [Test]
        public void VirtualMachineInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VirtualMachine
            //Assert.IsInstanceOfType<VirtualMachine> (instance, "variable 'instance' is a VirtualMachine");
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'RunTimeInfo'
        /// </summary>
        [Test]
        public void RunTimeInfoTest()
        {
            // TODO unit test for the property 'RunTimeInfo'
        }

    }

}
