/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VirtualMachineRuntimeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VirtualMachineRuntimeInfoTests
    {
        // TODO uncomment below to declare an instance variable for VirtualMachineRuntimeInfo
        //private VirtualMachineRuntimeInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VirtualMachineRuntimeInfo
            //instance = new VirtualMachineRuntimeInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VirtualMachineRuntimeInfo
        /// </summary>
        [Test]
        public void VirtualMachineRuntimeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VirtualMachineRuntimeInfo
            //Assert.IsInstanceOfType<VirtualMachineRuntimeInfo> (instance, "variable 'instance' is a VirtualMachineRuntimeInfo");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Moid'
        /// </summary>
        [Test]
        public void MoidTest()
        {
            // TODO unit test for the property 'Moid'
        }
        /// <summary>
        /// Test the property 'VmxPath'
        /// </summary>
        [Test]
        public void VmxPathTest()
        {
            // TODO unit test for the property 'VmxPath'
        }
        /// <summary>
        /// Test the property 'Folder'
        /// </summary>
        [Test]
        public void FolderTest()
        {
            // TODO unit test for the property 'Folder'
        }
        /// <summary>
        /// Test the property 'ResourcePool'
        /// </summary>
        [Test]
        public void ResourcePoolTest()
        {
            // TODO unit test for the property 'ResourcePool'
        }
        /// <summary>
        /// Test the property 'HostName'
        /// </summary>
        [Test]
        public void HostNameTest()
        {
            // TODO unit test for the property 'HostName'
        }
        /// <summary>
        /// Test the property 'NumCpu'
        /// </summary>
        [Test]
        public void NumCpuTest()
        {
            // TODO unit test for the property 'NumCpu'
        }
        /// <summary>
        /// Test the property 'GuestId'
        /// </summary>
        [Test]
        public void GuestIdTest()
        {
            // TODO unit test for the property 'GuestId'
        }
        /// <summary>
        /// Test the property 'GuestFullName'
        /// </summary>
        [Test]
        public void GuestFullNameTest()
        {
            // TODO unit test for the property 'GuestFullName'
        }
        /// <summary>
        /// Test the property 'GuestFamily'
        /// </summary>
        [Test]
        public void GuestFamilyTest()
        {
            // TODO unit test for the property 'GuestFamily'
        }
        /// <summary>
        /// Test the property 'GuestState'
        /// </summary>
        [Test]
        public void GuestStateTest()
        {
            // TODO unit test for the property 'GuestState'
        }
        /// <summary>
        /// Test the property 'ProvisionedSize'
        /// </summary>
        [Test]
        public void ProvisionedSizeTest()
        {
            // TODO unit test for the property 'ProvisionedSize'
        }
        /// <summary>
        /// Test the property 'UsedSize'
        /// </summary>
        [Test]
        public void UsedSizeTest()
        {
            // TODO unit test for the property 'UsedSize'
        }
        /// <summary>
        /// Test the property 'CpuUsage'
        /// </summary>
        [Test]
        public void CpuUsageTest()
        {
            // TODO unit test for the property 'CpuUsage'
        }
        /// <summary>
        /// Test the property 'MemoryMB'
        /// </summary>
        [Test]
        public void MemoryMBTest()
        {
            // TODO unit test for the property 'MemoryMB'
        }
        /// <summary>
        /// Test the property 'MemoryUsage'
        /// </summary>
        [Test]
        public void MemoryUsageTest()
        {
            // TODO unit test for the property 'MemoryUsage'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'PowerState'
        /// </summary>
        [Test]
        public void PowerStateTest()
        {
            // TODO unit test for the property 'PowerState'
        }
        /// <summary>
        /// Test the property 'ConnectionState'
        /// </summary>
        [Test]
        public void ConnectionStateTest()
        {
            // TODO unit test for the property 'ConnectionState'
        }
        /// <summary>
        /// Test the property 'DvsDeviceNetworkMaps'
        /// </summary>
        [Test]
        public void DvsDeviceNetworkMapsTest()
        {
            // TODO unit test for the property 'DvsDeviceNetworkMaps'
        }

    }

}
