/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VlanReplication
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VlanReplicationTests
    {
        // TODO uncomment below to declare an instance variable for VlanReplication
        //private VlanReplication instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VlanReplication
            //instance = new VlanReplication();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VlanReplication
        /// </summary>
        [Test]
        public void VlanReplicationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VlanReplication
            //Assert.IsInstanceOfType<VlanReplication> (instance, "variable 'instance' is a VlanReplication");
        }

        /// <summary>
        /// Test the property 'UcsmHostname'
        /// </summary>
        [Test]
        public void UcsmHostnameTest()
        {
            // TODO unit test for the property 'UcsmHostname'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'VlanName'
        /// </summary>
        [Test]
        public void VlanNameTest()
        {
            // TODO unit test for the property 'VlanName'
        }

    }

}
