/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VmCloneSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VmCloneSpecTests
    {
        // TODO uncomment below to declare an instance variable for VmCloneSpec
        //private VmCloneSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VmCloneSpec
            //instance = new VmCloneSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VmCloneSpec
        /// </summary>
        [Test]
        public void VmCloneSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VmCloneSpec
            //Assert.IsInstanceOfType<VmCloneSpec> (instance, "variable 'instance' is a VmCloneSpec");
        }

        /// <summary>
        /// Test the property 'VmId'
        /// </summary>
        [Test]
        public void VmIdTest()
        {
            // TODO unit test for the property 'VmId'
        }
        /// <summary>
        /// Test the property 'VmName'
        /// </summary>
        [Test]
        public void VmNameTest()
        {
            // TODO unit test for the property 'VmName'
        }
        /// <summary>
        /// Test the property 'CloneNamePrefix'
        /// </summary>
        [Test]
        public void CloneNamePrefixTest()
        {
            // TODO unit test for the property 'CloneNamePrefix'
        }
        /// <summary>
        /// Test the property 'NumberOfClones'
        /// </summary>
        [Test]
        public void NumberOfClonesTest()
        {
            // TODO unit test for the property 'NumberOfClones'
        }
        /// <summary>
        /// Test the property 'Parallel'
        /// </summary>
        [Test]
        public void ParallelTest()
        {
            // TODO unit test for the property 'Parallel'
        }
        /// <summary>
        /// Test the property 'PowerOn'
        /// </summary>
        [Test]
        public void PowerOnTest()
        {
            // TODO unit test for the property 'PowerOn'
        }
        /// <summary>
        /// Test the property 'CustomSpecName'
        /// </summary>
        [Test]
        public void CustomSpecNameTest()
        {
            // TODO unit test for the property 'CustomSpecName'
        }
        /// <summary>
        /// Test the property 'VmGuestNamePrefix'
        /// </summary>
        [Test]
        public void VmGuestNamePrefixTest()
        {
            // TODO unit test for the property 'VmGuestNamePrefix'
        }
        /// <summary>
        /// Test the property 'CloneNameStartNumber'
        /// </summary>
        [Test]
        public void CloneNameStartNumberTest()
        {
            // TODO unit test for the property 'CloneNameStartNumber'
        }
        /// <summary>
        /// Test the property 'CloneNameIncrement'
        /// </summary>
        [Test]
        public void CloneNameIncrementTest()
        {
            // TODO unit test for the property 'CloneNameIncrement'
        }
        /// <summary>
        /// Test the property 'ResourcePoolId'
        /// </summary>
        [Test]
        public void ResourcePoolIdTest()
        {
            // TODO unit test for the property 'ResourcePoolId'
        }
        /// <summary>
        /// Test the property 'ResourcePoolName'
        /// </summary>
        [Test]
        public void ResourcePoolNameTest()
        {
            // TODO unit test for the property 'ResourcePoolName'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
