/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VmProtectionSpaceUsage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VmProtectionSpaceUsageTests
    {
        // TODO uncomment below to declare an instance variable for VmProtectionSpaceUsage
        //private VmProtectionSpaceUsage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VmProtectionSpaceUsage
            //instance = new VmProtectionSpaceUsage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VmProtectionSpaceUsage
        /// </summary>
        [Test]
        public void VmProtectionSpaceUsageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VmProtectionSpaceUsage
            //Assert.IsInstanceOfType<VmProtectionSpaceUsage> (instance, "variable 'instance' is a VmProtectionSpaceUsage");
        }

        /// <summary>
        /// Test the property 'SpaceUsage'
        /// </summary>
        [Test]
        public void SpaceUsageTest()
        {
            // TODO unit test for the property 'SpaceUsage'
        }

    }

}
