/* 
 * HyperFlex AAA [Authentication, Authorization and Accounting]
 *
 * REST API to authenticate users and grant/validate access tokens. AAA provides role based access control to REST APIs which allows users to perform various operations on resources in a cluster.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: techsupport@springpathinc.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRefreshAccessTokenApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Validate and refresh token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">Grant Type is a method by which authentication is performed. Grant types currently supported by AAA are: refresh_token (Grant Refresh token)</param>
        /// <param name="body">The payload of post request should contain user credentials - user name and password.</param>
        /// <returns>AccessTokenEnvelope</returns>
        AccessTokenEnvelope RefreshAccessToken (string grantType, RefreshTokenEnvelope body);

        /// <summary>
        /// Validate and refresh token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">Grant Type is a method by which authentication is performed. Grant types currently supported by AAA are: refresh_token (Grant Refresh token)</param>
        /// <param name="body">The payload of post request should contain user credentials - user name and password.</param>
        /// <returns>ApiResponse of AccessTokenEnvelope</returns>
        ApiResponse<AccessTokenEnvelope> RefreshAccessTokenWithHttpInfo (string grantType, RefreshTokenEnvelope body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Validate and refresh token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">Grant Type is a method by which authentication is performed. Grant types currently supported by AAA are: refresh_token (Grant Refresh token)</param>
        /// <param name="body">The payload of post request should contain user credentials - user name and password.</param>
        /// <returns>Task of AccessTokenEnvelope</returns>
        System.Threading.Tasks.Task<AccessTokenEnvelope> RefreshAccessTokenAsync (string grantType, RefreshTokenEnvelope body);

        /// <summary>
        /// Validate and refresh token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">Grant Type is a method by which authentication is performed. Grant types currently supported by AAA are: refresh_token (Grant Refresh token)</param>
        /// <param name="body">The payload of post request should contain user credentials - user name and password.</param>
        /// <returns>Task of ApiResponse (AccessTokenEnvelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<AccessTokenEnvelope>> RefreshAccessTokenAsyncWithHttpInfo (string grantType, RefreshTokenEnvelope body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RefreshAccessTokenApi : IRefreshAccessTokenApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RefreshAccessTokenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RefreshAccessTokenApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RefreshAccessTokenApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RefreshAccessTokenApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Validate and refresh token 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">Grant Type is a method by which authentication is performed. Grant types currently supported by AAA are: refresh_token (Grant Refresh token)</param>
        /// <param name="body">The payload of post request should contain user credentials - user name and password.</param>
        /// <returns>AccessTokenEnvelope</returns>
        public AccessTokenEnvelope RefreshAccessToken (string grantType, RefreshTokenEnvelope body)
        {
             ApiResponse<AccessTokenEnvelope> localVarResponse = RefreshAccessTokenWithHttpInfo(grantType, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Validate and refresh token 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">Grant Type is a method by which authentication is performed. Grant types currently supported by AAA are: refresh_token (Grant Refresh token)</param>
        /// <param name="body">The payload of post request should contain user credentials - user name and password.</param>
        /// <returns>ApiResponse of AccessTokenEnvelope</returns>
        public ApiResponse< AccessTokenEnvelope > RefreshAccessTokenWithHttpInfo (string grantType, RefreshTokenEnvelope body)
        {
            // verify the required parameter 'grantType' is set
            if (grantType == null)
                throw new ApiException(400, "Missing required parameter 'grantType' when calling RefreshAccessTokenApi->RefreshAccessToken");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RefreshAccessTokenApi->RefreshAccessToken");

            var localVarPath = "/token";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (grantType != null) localVarQueryParams.Add("grant_type", Configuration.ApiClient.ParameterToString(grantType)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RefreshAccessToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccessTokenEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AccessTokenEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccessTokenEnvelope)));
        }

        /// <summary>
        /// Validate and refresh token 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">Grant Type is a method by which authentication is performed. Grant types currently supported by AAA are: refresh_token (Grant Refresh token)</param>
        /// <param name="body">The payload of post request should contain user credentials - user name and password.</param>
        /// <returns>Task of AccessTokenEnvelope</returns>
        public async System.Threading.Tasks.Task<AccessTokenEnvelope> RefreshAccessTokenAsync (string grantType, RefreshTokenEnvelope body)
        {
             ApiResponse<AccessTokenEnvelope> localVarResponse = await RefreshAccessTokenAsyncWithHttpInfo(grantType, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Validate and refresh token 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">Grant Type is a method by which authentication is performed. Grant types currently supported by AAA are: refresh_token (Grant Refresh token)</param>
        /// <param name="body">The payload of post request should contain user credentials - user name and password.</param>
        /// <returns>Task of ApiResponse (AccessTokenEnvelope)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AccessTokenEnvelope>> RefreshAccessTokenAsyncWithHttpInfo (string grantType, RefreshTokenEnvelope body)
        {
            // verify the required parameter 'grantType' is set
            if (grantType == null)
                throw new ApiException(400, "Missing required parameter 'grantType' when calling RefreshAccessTokenApi->RefreshAccessToken");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RefreshAccessTokenApi->RefreshAccessToken");

            var localVarPath = "/token";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (grantType != null) localVarQueryParams.Add("grant_type", Configuration.ApiClient.ParameterToString(grantType)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RefreshAccessToken", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccessTokenEnvelope>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AccessTokenEnvelope) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccessTokenEnvelope)));
        }

    }
}
