/* 
 * Swagger Server
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RecoveryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RecoveryApiTests
    {
        private RecoveryApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RecoveryApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecoveryApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RecoveryApi
            //Assert.IsInstanceOfType(typeof(RecoveryApi), instance, "instance is a RecoveryApi");
        }

        
        /// <summary>
        /// Test OpDpGroupHaltPut
        /// </summary>
        [Test]
        public void OpDpGroupHaltPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string groupId = null;
            //string acceptLanguage = null;
            //instance.OpDpGroupHaltPut(groupId, acceptLanguage);
            
        }
        
        /// <summary>
        /// Test OpDpVmHaltPut
        /// </summary>
        [Test]
        public void OpDpVmHaltPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string vmId = null;
            //string acceptLanguage = null;
            //instance.OpDpVmHaltPut(vmId, acceptLanguage);
            
        }
        
        /// <summary>
        /// Test OpDpVmRecoveryFailoverPut
        /// </summary>
        [Test]
        public void OpDpVmRecoveryFailoverPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string vmId = null;
            //RecoverVmOptions body = null;
            //string acceptLanguage = null;
            //var response = instance.OpDpVmRecoveryFailoverPut(vmId, body, acceptLanguage);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test OpDpVmRecoveryJobsGet
        /// </summary>
        [Test]
        public void OpDpVmRecoveryJobsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string acceptLanguage = null;
            //var response = instance.OpDpVmRecoveryJobsGet(acceptLanguage);
            //Assert.IsInstanceOf<List<Job>> (response, "response is List<Job>");
        }
        
        /// <summary>
        /// Test OpDpVmRecoveryJobsJobIdGet
        /// </summary>
        [Test]
        public void OpDpVmRecoveryJobsJobIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //string acceptLanguage = null;
            //var response = instance.OpDpVmRecoveryJobsJobIdGet(jobId, acceptLanguage);
            //Assert.IsInstanceOf<List<Job>> (response, "response is List<Job>");
        }
        
        /// <summary>
        /// Test OpDpVmRecoveryTestPut
        /// </summary>
        [Test]
        public void OpDpVmRecoveryTestPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string vmId = null;
            //RecoverVmOptions body = null;
            //string acceptLanguage = null;
            //var response = instance.OpDpVmRecoveryTestPut(vmId, body, acceptLanguage);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
